keynote: []
docsify:
  - 'an-algorithm-used-for-image-text-detect.md'
  - 'study-facial-expression-recognition.md'
  - 'medical-applications-on-ai-facial-expression-recognition.md'
  - 'facial-expression-recognition-technology-based-on-neural-network.md'
  - 'ocr-overview.md'
  - 'deepseek-applications.md'
gitbook: []
ignore: []