keynote: []
docsify:
  - 'an-algorithm-used-for-image-text-detect.md'
  - 'introduce-the-post-processing.md'
  - 'introduce-the-text-detect-method.md'
gitbook: []
ignore: []
copy:
  - 'demo'
  - 'image'
